name: Python application

on:
  schedule:
    - cron:  '00 */2 * * *'  
  workflow_dispatch:
    inputs:
      manualrun:
        description: 'Manually run workflow'     
        required: true
  #push:
  #  branches:
  #    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; pip install pymongo[srv]; fi
    - name: html parser
      env:
        MONGO: ${{ secrets.MONGO }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
        TWITTER_TOKEN_SECRET: ${{ secrets.TWITTER_TOKEN_SECRET }} 
      run: |
          python html_proc.py  
          git status
